name: segmented_progress_bar
description: A customizable segmented progress bar
version: 1.1.0
homepage: https://github.com/marjandn/segmented_progress_bar

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
